// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentStatus } from "./DocumentStatus";

export type DocumentSummary = {
  id: string;
  title: string;
  fileName: string;
  status: DocumentStatus;
  createdAt: string;
};
