// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentAuthor } from "./DocumentAuthor";
import type { DocumentStatus } from "./DocumentStatus";

export type DocumentDetail = {
  id: string;
  title: string;
  fileName: string;
  status: DocumentStatus;
  content: string;
  createdAt: string;
  createdBy: DocumentAuthor;
};
