// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentStatus } from "./DocumentStatus";

export type EvidenceRef = {
  documentId: string;
  title: string;
  fileName: string;
  status: DocumentStatus;
};
