// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Review } from "./Review";

export type ListMyReviewsResponse = { items: Array<Review> };
