// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentSummary } from "./DocumentSummary";

export type ListDocumentsResponse = { items: Array<DocumentSummary> };
