// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressItem } from "./ProgressItem";

/**
 * Counts come from the investor's own reviews only, never from documents (README).
 */
export type MyProgressResponse = {
  totalCount: number;
  writtenCount: number;
  unwrittenCount: number;
  satisfiedCount: number;
  needsInformationCount: number;
  items: Array<ProgressItem>;
};
