// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Criterion } from "./Criterion";
import type { Review } from "./Review";

export type ProgressItem = { criterion: Criterion; review: Review | null };
