// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceRef } from "./EvidenceRef";
import type { ReviewDecision } from "./ReviewDecision";

export type Review = {
  id: string;
  criterionId: string;
  decision: ReviewDecision;
  comment: string;
  evidence: Array<EvidenceRef>;
  createdAt: string;
  updatedAt: string;
};
