// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewDecision } from "./ReviewDecision";

export type SaveReviewParams = {
  criterionId: string;
  decision: ReviewDecision;
  comment: string;
  evidenceDocumentIds: Array<string>;
};
