import type { Locale } from "@interview/plugin-sdk";

const ko = {
  title: "검토",
  loading: "불러오는 중입니다.",
  loadError: "데이터를 불러오지 못했습니다. 다시 시도해주세요.",
  retry: "다시 시도",
  pageNotFound: "페이지를 찾을 수 없습니다.",
  companyNotice:
    "검토·현황은 투자자만 사용할 수 있습니다. 기업 담당자는 검토 기준만 볼 수 있습니다.",
  investorOnly: "검토는 투자자만 작성할 수 있습니다.",
  criteriaHeading: "검토 기준",
  reviewQuestion: "검토 질문",
  writeReview: "작성·수정",
  backToCriteria: "검토 기준 목록으로",
  criterionNotFound: "검토 기준을 찾을 수 없습니다.",
  decision: "판단",
  satisfied: "확인함",
  needsInformation: "추가 확인 필요",
  comment: "의견",
  commentCount: "자",
  evidence: "근거 자료",
  evidenceHint: "준비 완료된 자료만 선택할 수 있습니다. 1~20개",
  notReadyReason: "준비 완료된 자료만 근거로 선택할 수 있습니다.",
  noDocuments: "등록된 자료가 없습니다. 자료를 먼저 등록해야 근거를 선택할 수 있습니다.",
  droppedEvidence: "처리 중이거나 실패 상태로 바뀌어 근거 선택에서 뺀 자료:",
  viewDocument: "보기",
  save: "저장",
  saving: "저장 중입니다.",
  lastSaved: "마지막 저장",
  decisionRequired: "판단을 선택해주세요.",
  commentBlank: "의견을 입력해주세요. 공백만으로는 저장할 수 없습니다.",
  commentTooLong: "의견은 2000자 이하로 입력해주세요.",
  commentControl: "의견에는 줄바꿈과 탭 외의 제어 문자를 넣을 수 없습니다.",
  evidenceRequired: "근거 자료를 하나 이상 선택해주세요.",
  evidenceTooMany: "근거 자료는 20개까지 선택할 수 있습니다.",
  saveInvalid:
    "저장하지 못했습니다. 입력값과 선택한 자료의 상태를 확인해주세요. 자료 목록을 새로 불러왔습니다.",
  saveNotFound: "선택한 자료나 검토 기준을 찾을 수 없습니다. 자료 목록을 새로 불러왔습니다.",
  saveForbidden: "검토를 저장할 권한이 없습니다.",
  saveFailed: "저장하지 못했습니다. 다시 시도해주세요.",
  documentNotFound: "자료를 찾을 수 없습니다.",
  fileName: "파일명",
  status: "상태",
  content: "본문",
  statusReady: "준비 완료",
  statusProcessing: "처리 중",
  statusFailed: "처리 실패",
  progressHeading: "내 검토 현황",
  progressNotice: "개인 검토 진행 상태이며 회사 전체의 합의나 투자 승인이 아닙니다.",
  written: "작성",
  unwritten: "미작성",
  savedCriterion: "저장했습니다:",
};

export type Text = Record<keyof typeof ko, string>;
export type TextKey = keyof Text;

const en: Text = {
  title: "Review",
  loading: "Loading…",
  loadError: "Could not load data. Please try again.",
  retry: "Try again",
  pageNotFound: "Page not found.",
  companyNotice:
    "Reviews and progress are for investors only. Company members can view the criteria.",
  investorOnly: "Only investors can write reviews.",
  criteriaHeading: "Review criteria",
  reviewQuestion: "Review question",
  writeReview: "Write or edit",
  backToCriteria: "Back to criteria",
  criterionNotFound: "Review criterion not found.",
  decision: "Decision",
  satisfied: "Satisfied",
  needsInformation: "Needs information",
  comment: "Comment",
  commentCount: "characters",
  evidence: "Evidence documents",
  evidenceHint: "Only ready documents can be selected. 1-20 documents.",
  notReadyReason: "Only ready documents can be used as evidence.",
  noDocuments: "No documents have been uploaded yet.",
  droppedEvidence: "Removed from evidence because they are now processing or failed:",
  viewDocument: "View",
  save: "Save",
  saving: "Saving…",
  lastSaved: "Last saved",
  decisionRequired: "Choose a decision.",
  commentBlank: "Enter a comment. Whitespace only is not allowed.",
  commentTooLong: "Comments must be 2000 characters or fewer.",
  commentControl: "Comments cannot contain control characters other than line breaks and tabs.",
  evidenceRequired: "Select at least one evidence document.",
  evidenceTooMany: "Select up to 20 evidence documents.",
  saveInvalid:
    "Could not save. Check your input and the selected documents. The document list was reloaded.",
  saveNotFound:
    "A selected document or the criterion was not found. The document list was reloaded.",
  saveForbidden: "You do not have permission to save reviews.",
  saveFailed: "Could not save. Please try again.",
  documentNotFound: "Document not found.",
  fileName: "File name",
  status: "Status",
  content: "Content",
  statusReady: "Ready",
  statusProcessing: "Processing",
  statusFailed: "Failed",
  progressHeading: "My review progress",
  progressNotice:
    "This is your personal review progress, not a company-wide agreement or investment approval.",
  written: "Written",
  unwritten: "Not written",
  savedCriterion: "Saved:",
};

export function textFor(locale: Locale): Text {
  return locale === "ko" ? ko : en;
}
